version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8081"
    environment:
      - NETBOX_URL=value
      - NETBOX_KEY=value
    restart: on-failure