services:
  backend:
    build:
      context: ./designation.gen.back/designation.gen
      dockerfile: Dockerfile
    container_name: clh-manager-backend
    ports:
      - "8080:8080"
    volumes:
      - sqlite-data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./designation.gen.front/designations.gen
      dockerfile: Dockerfile
    container_name: clh-manager-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlite-data:
    driver: local
